#!/usr/bin/env bash

# Source this file from any directory to use the repository's standard data layout.
script_path=${BASH_SOURCE[0]:-$0}
VIDEO_HARNESS_ROOT=${VIDEO_HARNESS_ROOT:-$(cd "$(dirname "${script_path}")/.." && pwd)}
VIDEO_HARNESS_DATA_ROOT=${VIDEO_HARNESS_DATA_ROOT:-${VIDEO_HARNESS_ROOT}/data}
ROBODOJO_REPO_ID=${ROBODOJO_REPO_ID:-RoboDojo_lerobot_v30_video}
ROBODOJO_DATASET_ROOT=${ROBODOJO_DATASET_ROOT:-${VIDEO_HARNESS_DATA_ROOT}/${ROBODOJO_REPO_ID}}
VIDEO_HARNESS_RUN_ROOT=${VIDEO_HARNESS_RUN_ROOT:-${VIDEO_HARNESS_DATA_ROOT}/video-harness/default}
GUIDE_DOCUMENTS_ROOT=${GUIDE_DOCUMENTS_ROOT:-${VIDEO_HARNESS_RUN_ROOT}/documents-openai}
GUIDE_MATERIALIZATION_CACHE_ROOT=${GUIDE_MATERIALIZATION_CACHE_ROOT:-${VIDEO_HARNESS_DATA_ROOT}/guide-cache/default}
GUIDED_RUN_ROOT=${GUIDED_RUN_ROOT:-${VIDEO_HARNESS_DATA_ROOT}/runs/guided-pi05}
HF_LEROBOT_HOME=${HF_LEROBOT_HOME:-${VIDEO_HARNESS_DATA_ROOT}}

export VIDEO_HARNESS_ROOT VIDEO_HARNESS_DATA_ROOT
export ROBODOJO_REPO_ID ROBODOJO_DATASET_ROOT HF_LEROBOT_HOME
export VIDEO_HARNESS_RUN_ROOT GUIDE_DOCUMENTS_ROOT
export GUIDE_MATERIALIZATION_CACHE_ROOT GUIDED_RUN_ROOT
unset script_path
